[package]
name = "iam-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com"]
edition = "2018"
description = "Example usage of the IAM service"

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-iam = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-hyper = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
tokio = { version = "1", features = ["full"]}
serde_json = "1"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
